AllCops:
  RunRailsCops: true
  DisplayStyleGuide: true
  DisplayCopNames: true
  Include:
    - '**/Gemfile'
  Exclude:
    - 'bin/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/UnneededPercentQ:
  Exclude:
    - '*.gemspec'

Style/Filename
  Exclude:
    - 'Rakefile'